### PR TITLE
feat: add named lootrun tasks

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Comment by kristofbolyai** [comment]
This replaced the reference data. The names are hand-added, but collected from the Wynn-Wiki.

**Comment by magicus** [comment]
Do you have any idea where the wiki got the names from? Are they official, or just dreamt-up by the wiki editors?

**Comment by kristofbolyai** [comment]
I don't think they are official, but more like names the community agreed upon.

**Comment by magicus** [comment]
Or at least the wiki editors. :) Very well, let's keep them. At some point, I really like to make a clear distinction between mapdata sources that are official, and that are community-provided. So we can provide the latter as a convenience, but make it clear that it is not official. We can probably make the naming of lootruns fit into that system quite well, so we have an official source of lootrun coordinates, and a community-contributed one which adds on the names...

**Pull request merged**
