### PR TITLE
Add and update discoveries to match 2.0

### PR DESCRIPTION
**Pull request by coehlrich**
Updated level requirement of Black Road, Sanctuary Bridge, and Time Valley.
Added Llevigar's Secret Library, Faltach Manor, Ways of the Wicked, and Far Above the Clouds.
Updated the requirements for ultimate discoveries.
Renamed Leadin Orc Fort.

### CODE REVIEW

**Comment by magicus** [comment]
What is the source for this data?

**Comment by coehlrich** [comment]
It was exported from my quest book on my class that has all every discovery then passes through an excel workbook to convert the export to json while adding secret discovery requirements and comparing it to the existing discoveries.json file.

**Comment by magicus** [comment]
I see. Too bad that this data is so tricky to get. :( Have you corroborated it with the wiki https://wynncraft.fandom.com/wiki/Secret_Discoveries? Also, how do you export data from the quest book? (Just curious)

**Review by magicus — APPROVED** [review]
Change is good, but integration should perhaps wait until 2.0 goes live..?

**Comment by coehlrich** [comment]
I used to use /exportdiscoveries but now I use https://gist.github.com/coehlrich/00ab3f576c3934a93c8b7a004cd54417 for 1.19.2

**Pull request merged**
