### PR TITLE
Remove artemis old impl

### PR DESCRIPTION
**Pull request by Incompleteusern**

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Wait a few weeks.. Old artemis users would not like this.

**Comment by magicus** [comment]
Or just let it hang around even longer. There's no rush to remove this. For all I care it can stay more or less forever...

**Comment by kristofbolyai** [comment]
If this exists remove the link from https://api.wynntils.com/webapi too

**Comment by Incompleteusern** [comment]
> If this exists remove the link from https://api.wynntils.com/webapi too

It is done so

**Review by magicus — CHANGES_REQUESTED** [review]
Seriously. Delay this some months...

**Review by magicus — APPROVED** [review]
Yeah, lets do this now.

**Pull request merged**
